---

- name: ftp server setup
  remote_user: vagrant
  become: yes

  hosts:
  - ftp

  tasks:
  - name: Install packages
    package:
      name: "vsftpd"
      state: present
  
  - name: Enable and run the service
    service:
      name: "vsftpd"
      state: started
      enabled: yes
